### ISSUE TITLE
parseQuery fails when bind variable contains parenthesis 

### ISSUE THREAD

**Issue by pgonzaleznetwork** [paustint/soql-parser-js#153]
```
let query = 'select id from account where id in :accountMap.keySet();
parseQuery(query,{allowApexBindVariables:true});
```

Result

```
(node:55304) UnhandledPromiseRejectionWarning: NoViableAltException: Expecting: one of these possible Token sequences:
  1. [AVG, L_PAREN]
  2. [COUNT, L_PAREN]
  3. [COUNT_DISTINCT, L_PAREN]
  4. [MIN, L_PAREN]
  5. [MAX, L_PAREN]
  6. [SUM, L_PAREN]
  7. [DISTANCE, L_PAREN]
  8. [CALENDAR_MONTH, L_PAREN]
  9. [CALENDAR_QUARTER, L_PAREN]
  10. [CALENDAR_YEAR, L_PAREN]
  11. [DAY_IN_MONTH, L_PAREN]
  12. [DAY_IN_WEEK, L_PAREN]
  13. [DAY_IN_YEAR, L_PAREN]
  14. [DAY_ONLY, L_PAREN]
  15. [FISCAL_MONTH, L_PAREN]
  16. [FISCAL_QUARTER, L_PAREN]
  17. [FISCAL_YEAR, L_PAREN]
  18. [HOUR_IN_DAY, L_PAREN]
  19. [WEEK_IN_MONTH, L_PAREN]
  20. [WEEK_IN_YEAR, L_PAREN]
  21. [FORMAT, L_PAREN]
  22. [toLabel, L_PAREN]
  23. [convertTimezone, L_PAREN]
  24. [convertCurrency, L_PAREN]
  25. [GROUPING, L_PAREN]
  26. [Identifier]
but found: ')'
```

```
at Object.parse (src/parser/parser.ts:704:11)
at Object.parseQuery (src/parser/visitor.ts:847:38)
```

If we remove the parenthesis from keySet(), then it works, i.e

```
let query = 'select id from account where id in :accountMap.keySet;//<< PARENTHESIS REMOVED
parseQuery(query,{allowApexBindVariables:true});
```

No error

**Use Case**

We are using this library in HappySoup.io to parse queries in apex classes to find where standard fields are used. This error would prevent us from parsing queries to see if a particular standard field is used.

Is there any way to allow for partial success? i.e if you can't parse the WHERE clause, at least we'd like to evaluate the SELECT one.

Thanks!

**Comment by paustint** [comment]
Thanks for the feedback - I like the idea about partial parsing and that would be useful for me as well.

I will look into it.

**Comment by paustint** [comment]
@pgonzaleznetwork - I am working on creating a release for the new version with support for partial query parsing.

* There is a new boolean option called `ignoreParseErrors`
* This does not apply to `isQueryValid` - because the query is not valid, so it is still reported as such
* The query still needs to be generally valid, it is only within a clause that invalid syntax would be able to be ignored
* If any part of a clause is invalid, the entire clause is removed from the output, otherwise it would have been a lot of code changes to support this.

```javascript
SELECT Id, (SELECT Id FROM Contacts WHERE Id IN :contactMap.keySet()) FROM Account WHERE Id IN :accountMap.keySet()

parseQuery(soqlQuery, { allowApexBindVariables: true, ignoreParseErrors: true });
```
**Output:**
```javascript
{
  "fields": [
    {
      "type": "Field",
      "field": "Id"
    },
    {
      "type": "FieldSubquery",
      "subquery": {
        "fields": [
          {
            "type": "Field",
            "field": "Id"
          }
        ],
        "relationshipName": "Contacts"
      }
    }
  ],
  "sObject": "Account"
}

```

---

I was considering adding some additional parser support for apex bind variables, like `accountMap.keySet()`, but then it turned out to be more problematic than I was expecting and as I thought about it, there are just too many variations that would need to be supported which would require a massive amount of work.

Example:
`WHERE Id IN :new Map<Id, SObject>([SELECT Id FROM account]).keySet()`

**For now, I am going to leave the existing parser logic for apex bind variables as-is**
